### ISSUE TITLE
pathway controlled value question

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#298]
Is the controlled value for https://dwc.tdwg.org/pw/#dwcpw_p011 really supposed to be 'publisGardenZooAquaria' and not 'publicGardenZooAquaria'?

**Comment by qgroom** [comment]
It was certainly intended to be `publi**c**GardenZooAquaria`
However, the original documentation (http://nora.nerc.ac.uk/id/eprint/519129/) refers to "Botanic gardens / zoo / aquaria".
I don't remember when it was changed to public rather than botanical, but to be consistent with the documentation I think it should be `botanicalGardensZooAquaria`. Other garden escapes are covered under the term `ornamentalNonHorticulture`.

**Comment by tucotuco** [comment]
Hmm. That is more than just a "clerical amendment". How would you like to proceed?

**Comment by tucotuco** [comment]
The paper we published has "public" as well. I recommend the clerical fix to "public" immediately, then decide if you want to pursue the normative change through the onerous path.

**Comment by qgroom** [comment]
OK, just leave it as public for now. Certainly, we point to the documentation very clearly and one can't really apply these terms correctly without at least glancing at it.

**Comment by baskaufs** [comment]
The best thing would be to change labels as desired but not to change the controlled string. However, in this case I think the controlled value string should be changed because forever people will look at it and probably "correct" it to `publicGardenZooAquaria`.  

Given that changing the controlled value string is a change to something normative, we need to make sure that it is announced. However, I think this could genuinely be considered to be an error so I don't think we need to go through a formal change process. The sooner it gets fixed, the less likely somebody is going to start using the "wrong" controlled value.

**Comment by tucotuco** [comment]
I have in the queue a series of issues with the label "Process - implement"
that need not go through review. As I go through updating the GBIF
extensions I may find more. I'll alert when a new release can be made with
all such changes incorporated.

**Comment by baskaufs** [comment]
If you can get the full set of updates/corrections together, we should release the corrected versions ASAP. I've been tied up with another conference today and still not recovered from TDWG, but I'm trying to work my way back through the emails that have been piling up.

**Comment by tucotuco** [comment]
Now that I have finished the painful update to the GBIF extensions, this is
next.

**Comment by tucotuco** [comment]
Converting to a change term issue.

## Change term

* Submitter: John Wieczorek
* Justification (why is this change necessary?): typographical error
* Proponents (who needs this change): Everyone

Proposed new attributes of the term:
Change 'publis' to 'public' in
* Preferred label: <term dc:title='publisGardenZooAquaria' xml:lang='en'/>

**Comment by baskaufs** [comment]
Fixed in https://github.com/tdwg/rs.tdwg.org/commit/c2dd0fd452f5aef44ec718f7182c0cffa53cde34 and https://github.com/tdwg/dwc/commit/e9d97e3106d46aff10169e1687af5bd8ac451289
